### ISSUE TITLE
Remove the dynamic value behavior from the ZbMap

### ISSUE THREAD

**Issue by Zelldon** [camunda-zeebe/zb-util#30]
Currently we store value length as header and if a block is updated we check if the value is larger then the size etc. also if so we have to move the other blocks to fit. Since currently we don't use this feature i would suggest to remove this. This save us some memory and also time for the comparisons.

**Comment by saig0** [comment]
Review Hints:
* BucketArray: getBlockLength -> don't use the arguments
* BucketArray: don't need to store the bucket length in header if we have the fill count and a fixed key+value length
